### ISSUE TITLE
Typo TCS Ch5 pg 190

### ISSUE THREAD

**Issue by kathryn-smith** [uvatoc/uvatoc.github.io#2]
In the paragraph right above the bolded "Take Away Points", it states 
"Otherwise, EVAL𝑠,𝑛,𝑚(𝑝𝑥) equals 0^𝑚 (this case is not very important: you can simply think of 0^𝑛 as some “junk value” that indicates an error)."

I think the 0^n in the second term should be 0^m, as 0^n is never mentioned anywhere before this.

**Comment by evansuva** [comment]
I think you mean to submit this for the book: https://github.com/boazbk/tcs/issues

**Comment by kathryn-smith** [comment]
you're right. thanks!
